#!/usr/bin/env bash

FUZZER=radamsa
APP=./vigenere
SEED=plaintext.txt
FUZZED=fuzzed.txt
crashes=0

rm -fr ./crashes
mkdir ./crashes

# Fuzz forever
while true; do

    # Show date
    date

    # Fuzz the original valid file and save output
    $FUZZER $SEED > $FUZZED

    # Execute the application using the fuzzed file as input
    $APP -E -k 'MYKEYISHERE' -o 'ciphertext.txt' -i $FUZZED

    # Save the exit status
    exit_status=$?

    echo "-----------------------------"
    echo "Exit status: ${exit_status}"

    if [ $exit_status -gt 1 ]; then
        save=./crashes/crash-$(date +%Y.%m.%d-%H.%M.%S).txt
        echo "Saving crash file to ${save}"
        cp $FUZZED $save
        crashes=$((crashes+1)) 
        sleep 3
    fi

    echo "Crashes: ${crashes}"
    echo "-----------------------------"

    sleep 1

done
