version: "3.9"
services:
  http:
    build: .
    environment:
      - PORT=12345
      - USE_TLS=0
    ports:
      - "12345:12345"
  https:
    build: .
    environment:
      - USE_TLS=1
      - PORT=54321
    ports:
      - "54321:54321"