#!/usr/bin/env bash
export DIR="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
sudo apt-get update
sudo apt-get install build-essential gdb gnuplot -y
cd /tmp
rm -fr /tmp/afl
git clone https://github.com/AFLplusplus/AFLplusplus
cd ./AFLplusplus
make
sudo make install
cd ../
afl-gcc --version
rm -fr /tmp/AFLplusplus
cd "$DIR"
mkdir -p ./fuzzgoat/input ./fuzzgoat/output
cp ./good.json ./fuzzgoat/input/ 
cp ./testDriver ./testResults ./fuzzgoat/
