#!/usr/bin/env bash
DIR=./fuzzgoat
git clone https://github.com/fuzzstati0n/fuzzgoat.git
cd ./fuzzgoat
rm -fr ./.git ./input-files ./seed ./in
sed -i 's/^CC=afl-gcc/#CC=afl-gcc/' Makefile
sed -i '1i CC=gcc' Makefile
make
