#!/usr/bin/env bash
make stack2
export i=1
while true; do
    token=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w $i | head -n 1)
    echo ""
    echo "Command:         ./stack2 '$token'"
    echo "Length:          $i"
    ./stack2 "$token"
    if [ $? -eq 0 ]; then
        exit
    fi
    i=$((i+1))
    sleep 0.5
done
