#!/usr/bin/env bash
make stack3
export i=1
export token="A"
while true; do
    echo ""
    echo "Command:  ./stack3 '$token'"
    echo "Length:   $i"
    ./stack3 "$token"
    if [ $? -eq 0 ]; then
        exit
    fi
    i=$((i+1))
    token="${token}A"
    sleep 0.5

done
