.PHONY: clean

all: stack0 stack1 stack2 stack3 stack4

stack0: stack0.c
	gcc -o $@ $<

stack1: stack1.c
	gcc -o $@ $<

stack2: stack2.c
	gcc -o $@ $<

stack3: stack3.c
	gcc -o $@ $<

stack4: stack4.c
	gcc -o $@ $<

clean:
	rm -f stack0 stack1 stack2 stack3 stack4
